CD definitions

"../compilers/protoc.exe" --cpp_out=../bin/cpp/ --java_out=../bin/java/ --python_out=../bin/py/ service/user_manager/user_manager.proto service/toon/toon.proto service/toon/toon_external.proto service/storage/storage.proto service/server_pool/server_pool.proto service/search/search.proto service/search/search_types.proto service/presence/presence.proto service/presence/presence_types.proto service/notification/notification.proto service/game_utilities/game_utilities.proto service/game_master/game_factory.proto service/game_master/game_master.proto service/game_master/game_master_types.proto service/friends/friends_types.proto service/friends/definition/friends.proto service/exchange/exchange.proto service/exchange/exchange_types.proto service/channel_invitation/channel_invitation_types.proto service/channel_invitation/definition/channel_invitation.proto service/channel/channel_types.proto service/channel/definition/channel.proto service/authentication/authentication.proto lib/rpc/connection.proto lib/rpc/rpc.proto lib/protocol/attribute.proto lib/protocol/content_handle.proto lib/protocol/descriptor.proto lib/protocol/entity.proto lib/protocol/exchange.proto lib/protocol/exchange_object_provider.proto lib/protocol/invitation.proto lib/protocol/resource.proto lib/profanity/profanity.proto lib/config/process_config.proto google/protobuf/descriptor.proto service/followers/definition/followers.proto service/chat/definition/chat.proto service/chat/definition/chat_types.proto service/party/definition/party.proto Quest.proto GameMessage.proto Hero.proto Settings.proto Stats.proto Hireling.proto AttributeSerializer.proto Account.proto OnlineService.proto ItemCrafting.proto PartyMessage.proto Items.proto GBHandle.proto custom/protocol/rpc/rpc.proto

"../compilers/protoc.exe" --descriptor_set_out=../bin/all.descriptor --include_imports service/user_manager/user_manager.proto service/toon/toon.proto service/toon/toon_external.proto service/storage/storage.proto service/server_pool/server_pool.proto service/search/search.proto service/search/search_types.proto service/presence/presence.proto service/presence/presence_types.proto service/notification/notification.proto service/game_utilities/game_utilities.proto service/game_master/game_factory.proto service/game_master/game_master.proto service/game_master/game_master_types.proto service/friends/friends_types.proto service/friends/definition/friends.proto service/exchange/exchange.proto service/exchange/exchange_types.proto service/channel_invitation/channel_invitation_types.proto service/channel_invitation/definition/channel_invitation.proto service/channel/channel_types.proto service/channel/definition/channel.proto service/authentication/authentication.proto lib/rpc/connection.proto lib/rpc/rpc.proto lib/protocol/attribute.proto lib/protocol/content_handle.proto lib/protocol/descriptor.proto lib/protocol/entity.proto lib/protocol/exchange.proto lib/protocol/exchange_object_provider.proto lib/protocol/invitation.proto lib/protocol/resource.proto lib/profanity/profanity.proto lib/config/process_config.proto google/protobuf/descriptor.proto service/followers/definition/followers.proto service/chat/definition/chat.proto service/chat/definition/chat_types.proto service/party/definition/party.proto Quest.proto GameMessage.proto Hero.proto Settings.proto Stats.proto Hireling.proto AttributeSerializer.proto Account.proto OnlineService.proto ItemCrafting.proto PartyMessage.proto Items.proto GBHandle.proto custom/protocol/rpc/rpc.proto

"../compilers/protogen_csharp.exe" --proto_path=./ --include_imports -expand_namespace_directories=true -cls_compliance=false -output_directory=../bin/csharp/ lib\config\process_config.proto 
"../compilers/protogen_csharp.exe" --proto_path=./ --include_imports -expand_namespace_directories=true -cls_compliance=false -output_directory=../bin/csharp/ lib\profanity\profanity.proto 
"../compilers/protogen_csharp.exe" --proto_path=./ --include_imports -expand_namespace_directories=true -cls_compliance=false -output_directory=../bin/csharp/ lib\protocol\attribute.proto 
"../compilers/protogen_csharp.exe" --proto_path=./ --include_imports -expand_namespace_directories=true -cls_compliance=false -output_directory=../bin/csharp/ lib\protocol\content_handle.proto 
"../compilers/protogen_csharp.exe" --proto_path=./ --include_imports -expand_namespace_directories=true -cls_compliance=false -output_directory=../bin/csharp/ lib\protocol\descriptor.proto 
"../compilers/protogen_csharp.exe" --proto_path=./ --include_imports -expand_namespace_directories=true -cls_compliance=false -output_directory=../bin/csharp/ lib\protocol\entity.proto 
"../compilers/protogen_csharp.exe" --proto_path=./ --include_imports -expand_namespace_directories=true -cls_compliance=false -output_directory=../bin/csharp/ lib\protocol\exchange.proto 
"../compilers/protogen_csharp.exe" --proto_path=./ --include_imports -expand_namespace_directories=true -cls_compliance=false -output_directory=../bin/csharp/ lib\protocol\exchange_object_provider.proto 
"../compilers/protogen_csharp.exe" --proto_path=./ --include_imports -expand_namespace_directories=true -cls_compliance=false -output_directory=../bin/csharp/ lib\protocol\invitation.proto 
"../compilers/protogen_csharp.exe" --proto_path=./ --include_imports -expand_namespace_directories=true -cls_compliance=false -output_directory=../bin/csharp/ lib\protocol\resource.proto 
"../compilers/protogen_csharp.exe" --proto_path=./ --include_imports -expand_namespace_directories=true -cls_compliance=false -output_directory=../bin/csharp/ lib\rpc\connection.proto 
"../compilers/protogen_csharp.exe" --proto_path=./ --include_imports -expand_namespace_directories=true -cls_compliance=false -output_directory=../bin/csharp/ lib\rpc\rpc.proto 
"../compilers/protogen_csharp.exe" --proto_path=./ --include_imports -expand_namespace_directories=true -cls_compliance=false -output_directory=../bin/csharp/ service\authentication\authentication.proto 
"../compilers/protogen_csharp.exe" --proto_path=./ --include_imports -expand_namespace_directories=true -cls_compliance=false -output_directory=../bin/csharp/ service\channel\channel_types.proto 
"../compilers/protogen_csharp.exe" --proto_path=./ --include_imports -expand_namespace_directories=true -cls_compliance=false -output_directory=../bin/csharp/ service\channel\definition\channel.proto 
"../compilers/protogen_csharp.exe" --proto_path=./ --include_imports -expand_namespace_directories=true -cls_compliance=false -output_directory=../bin/csharp/ service\channel_invitation\channel_invitation_types.proto 
"../compilers/protogen_csharp.exe" --proto_path=./ --include_imports -expand_namespace_directories=true -cls_compliance=false -output_directory=../bin/csharp/ service\channel_invitation\definition\channel_invitation.proto 
"../compilers/protogen_csharp.exe" --proto_path=./ --include_imports -expand_namespace_directories=true -cls_compliance=false -output_directory=../bin/csharp/ service\exchange\exchange.proto 
"../compilers/protogen_csharp.exe" --proto_path=./ --include_imports -expand_namespace_directories=true -cls_compliance=false -output_directory=../bin/csharp/ service\exchange\exchange_types.proto 
"../compilers/protogen_csharp.exe" --proto_path=./ --include_imports -expand_namespace_directories=true -cls_compliance=false -output_directory=../bin/csharp/ service\friends\friends_types.proto 
"../compilers/protogen_csharp.exe" --proto_path=./ --include_imports -expand_namespace_directories=true -cls_compliance=false -output_directory=../bin/csharp/ service\friends\definition\friends.proto 
"../compilers/protogen_csharp.exe" --proto_path=./ --include_imports -expand_namespace_directories=true -cls_compliance=false -output_directory=../bin/csharp/ service\game_master\game_factory.proto 
"../compilers/protogen_csharp.exe" --proto_path=./ --include_imports -expand_namespace_directories=true -cls_compliance=false -output_directory=../bin/csharp/ service\game_master\game_master.proto 
"../compilers/protogen_csharp.exe" --proto_path=./ --include_imports -expand_namespace_directories=true -cls_compliance=false -output_directory=../bin/csharp/ service\game_master\game_master_types.proto 
"../compilers/protogen_csharp.exe" --proto_path=./ --include_imports -expand_namespace_directories=true -cls_compliance=false -output_directory=../bin/csharp/ service\game_utilities\game_utilities.proto 
"../compilers/protogen_csharp.exe" --proto_path=./ --include_imports -expand_namespace_directories=true -cls_compliance=false -output_directory=../bin/csharp/ service\notification\notification.proto 
"../compilers/protogen_csharp.exe" --proto_path=./ --include_imports -expand_namespace_directories=true -cls_compliance=false -output_directory=../bin/csharp/ service\presence\presence.proto 
"../compilers/protogen_csharp.exe" --proto_path=./ --include_imports -expand_namespace_directories=true -cls_compliance=false -output_directory=../bin/csharp/ service\presence\presence_types.proto 
"../compilers/protogen_csharp.exe" --proto_path=./ --include_imports -expand_namespace_directories=true -cls_compliance=false -output_directory=../bin/csharp/ service\search\search.proto 
"../compilers/protogen_csharp.exe" --proto_path=./ --include_imports -expand_namespace_directories=true -cls_compliance=false -output_directory=../bin/csharp/ service\search\search_types.proto 
"../compilers/protogen_csharp.exe" --proto_path=./ --include_imports -expand_namespace_directories=true -cls_compliance=false -output_directory=../bin/csharp/ service\server_pool\server_pool.proto 
"../compilers/protogen_csharp.exe" --proto_path=./ --include_imports -expand_namespace_directories=true -cls_compliance=false -output_directory=../bin/csharp/ service\storage\storage.proto 
"../compilers/protogen_csharp.exe" --proto_path=./ --include_imports -expand_namespace_directories=true -cls_compliance=false -output_directory=../bin/csharp/ service\toon\toon.proto 
"../compilers/protogen_csharp.exe" --proto_path=./ --include_imports -expand_namespace_directories=true -cls_compliance=false -output_directory=../bin/csharp/ service\toon\toon_external.proto 
"../compilers/protogen_csharp.exe" --proto_path=./ --include_imports -expand_namespace_directories=true -cls_compliance=false -output_directory=../bin/csharp/ service\user_manager\user_manager.proto 
"../compilers/protogen_csharp.exe" --proto_path=./ --include_imports -expand_namespace_directories=true -cls_compliance=false -output_directory=../bin/csharp/ service\followers\definition\followers.proto
"../compilers/protogen_csharp.exe" --proto_path=./ --include_imports -expand_namespace_directories=true -cls_compliance=false -output_directory=../bin/csharp/ service\chat\definition\chat.proto
"../compilers/protogen_csharp.exe" --proto_path=./ --include_imports -expand_namespace_directories=true -cls_compliance=false -output_directory=../bin/csharp/ service\chat\definition\chat_types.proto
"../compilers/protogen_csharp.exe" --proto_path=./ --include_imports -expand_namespace_directories=true -cls_compliance=false -output_directory=../bin/csharp/ service\party\definition\party.proto
"../compilers/protogen_csharp.exe" --proto_path=./ --include_imports -expand_namespace_directories=true -cls_compliance=false -output_directory=../bin/csharp/ Account.proto 
"../compilers/protogen_csharp.exe" --proto_path=./ --include_imports -expand_namespace_directories=true -cls_compliance=false -output_directory=../bin/csharp/ AttributeSerializer.proto 
"../compilers/protogen_csharp.exe" --proto_path=./ --include_imports -expand_namespace_directories=true -cls_compliance=false -output_directory=../bin/csharp/ GameMessage.proto 
"../compilers/protogen_csharp.exe" --proto_path=./ --include_imports -expand_namespace_directories=true -cls_compliance=false -output_directory=../bin/csharp/ GBHandle.proto 
"../compilers/protogen_csharp.exe" --proto_path=./ --include_imports -expand_namespace_directories=true -cls_compliance=false -output_directory=../bin/csharp/ Hero.proto 
"../compilers/protogen_csharp.exe" --proto_path=./ --include_imports -expand_namespace_directories=true -cls_compliance=false -output_directory=../bin/csharp/ Hireling.proto 
"../compilers/protogen_csharp.exe" --proto_path=./ --include_imports -expand_namespace_directories=true -cls_compliance=false -output_directory=../bin/csharp/ ItemCrafting.proto 
"../compilers/protogen_csharp.exe" --proto_path=./ --include_imports -expand_namespace_directories=true -cls_compliance=false -output_directory=../bin/csharp/ Items.proto 
"../compilers/protogen_csharp.exe" --proto_path=./ --include_imports -expand_namespace_directories=true -cls_compliance=false -output_directory=../bin/csharp/ OnlineService.proto 
"../compilers/protogen_csharp.exe" --proto_path=./ --include_imports -expand_namespace_directories=true -cls_compliance=false -output_directory=../bin/csharp/ PartyMessage.proto 
"../compilers/protogen_csharp.exe" --proto_path=./ --include_imports -expand_namespace_directories=true -cls_compliance=false -output_directory=../bin/csharp/ Quest.proto 
"../compilers/protogen_csharp.exe" --proto_path=./ --include_imports -expand_namespace_directories=true -cls_compliance=false -output_directory=../bin/csharp/ Settings.proto 
"../compilers/protogen_csharp.exe" --proto_path=./ --include_imports -expand_namespace_directories=true -cls_compliance=false -output_directory=../bin/csharp/ Stats.proto 
"../compilers/protogen_csharp.exe" --proto_path=./ --include_imports -expand_namespace_directories=true -cls_compliance=false -output_directory=../bin/csharp/ custom/protocol/rpc/rpc.proto


pause